sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234

  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0       #指定使用哪个数据库,一般有16个,默认为0,这里使用db0,不同数据库之间完全隔离
  #微信小程序相关配置信息
  wechat:
    appid: wxe7b01facce571ca4
    secret: d6a4546c80eeafefb85e05bcdd0bf952
    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath:
    apiV3Key: CZB51236435wxpay435434323FFDuv3
    weChatPayCertFilePath:
    notifyUrl: https://334e88e4.r8.cpolar.top/notify/paySuccess
    refundNotifyUrl: https://334e88e4.r8.cpolar.top/notify/refundSuccess
  #被引用的副配置文件
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tJfUgNu5EX8Qg19ePsS
    access-key-secret: 2hHoAE1zy3Hjd1ZCaqYCkWab6kWozY
    bucket-name: web-tlias-jian